website/apps/users/urls.py
# -*- coding: UTF-8 –*-

from django.conf.urls import url
from .views import UserInfoView, UploadImageView, UpdatePwdView, SendEmailCodeView, \
    UpdateEmailView, MyCommentView, PersonalView

urlpatterns = [
    # 用户信息
    url(r'^info/$', UserInfoView.as_view(), name="user_info"),
    # 用户头像上传
    url('image/upload/', UploadImageView.as_view(), name="image_upload"),
    # 用户个人中心修改密码
    url('update/pwd/', UpdatePwdView.as_view(), name="update_pwd"),
    # 专用于发送验证码的
    url('sendemail_code/', SendEmailCodeView.as_view(), name="sendemail_code"),
    # 我的评论
    url(r'^comment/$', MyCommentView.as_view(), name='comment'),
    # 我的帖子
    url(r'^personal/$', PersonalView.as_view(), name='personal'),
    # 更改邮箱
    url('update_email/', UpdateEmailView.as_view(), name="update_email")
]

website/extra_apps/DjangoUeditor/urls.py
# coding:utf-8
from django import VERSION
from .widgets import UEditorWidget, AdminUEditorWidget
from .views import get_ueditor_controller
from django.conf.urls import url

urlpatterns = [
    url(r'^controller/$', get_ueditor_controller),
]

website/website/urls.py
# -*- coding: UTF-8 –*-

"""website URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.views.static import serve
import xadmin
from website.settings import MEDIA_ROOT, STATIC_ROOT
from users.views import RegisterView, LoginView, IndexView, ForgetView, ActiveView, ResetView,\
    ModifyPwdView, LogoutView, AddTieView, TieDetailView, CommentView

urlpatterns = [
    # 后台
    url(r'^xadmin/', xadmin.site.urls),
    # 首页
    url(r'^$', IndexView.as_view(), name='index'),
    # 注册
    url(r'^register/$', RegisterView.as_view(), name='register'),
    # 激活用户
    url(r'^active/(?P<active_code>.*)/$', ActiveView.as_view(), name='user_active'),
    # 登录
    url(r'^login/$', LoginView.as_view(), name='login'),
    # 注销
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    # 忘记密码
    url(r'^forget/$', ForgetView.as_view(), name='forget_pwd'),
    url(r'^reset/(?P<active_code>.*)/$', ResetView.as_view(), name='reset_pwd'),
    url(r'^modify_pwd/$', ModifyPwdView.as_view(), name='modify_pwd'),

    # 添加帖子
    url(r'^add_tie/$', AddTieView.as_view(), name='add_tie'),
    # 帖子详情
    url(r'^detail/(?P<tie_id>\d+)/$', TieDetailView.as_view(), name='detail'),
    # 添加评论
    url(r'^comment/$', CommentView.as_view(), name='comment'),

    # 配置上传文件的访问处理函数
    url(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
    # 静态文件
    url(r'^static/(?P<path>.*)$', serve, {"document_root": STATIC_ROOT}),
    # 验证码相关url
    url(r'^captcha/', include('captcha.urls')),
    # 富文本相关url
    url(r'^ueditor/', include('ueditor.urls')),
    # 个人信息相关url
    url(r'^users/', include('users.urls', namespace='users')),

]


# 全局404和500页面
handler404 = 'users.views.page_not_found'
handler500 = 'users.views.page_error'

website/apps/users/forms.py
# -*- coding: UTF-8 –*-

from django import forms
from captcha.fields import CaptchaField
from users.models import UserProfile


class LoginForm(forms.Form):
    username = forms.CharField(required=True)
    password = forms.CharField(required=True)


class RegisterForm(forms.Form):
    email = forms.EmailField(required=True)
    password = forms.CharField(required=True, min_length=5)
    # 验证码,参数：错误信息
    captcha = CaptchaField(error_messages={'invalid': '验证码错误!'})


class ForgetForm(forms.Form):
    email = forms.EmailField(required=True)
    captcha = CaptchaField(error_messages={'invalid': '验证码错误!'})


class ModifyPwdForm(forms.Form):

    password1 = forms.CharField(required=True, min_length=5)
    password2 = forms.CharField(required=True, min_length=5)


class AddTieForm(forms.Form):
    title = forms.CharField(required=True)
    content = forms.CharField(required=True)
    board_id = forms.CharField(required=True)


class CommentForm(forms.Form):
    content = forms.CharField(required=True)


class UserInfoForm(forms.ModelForm):
    """
    用于个人中心修改个人信息
    """
    class Meta:
        model = UserProfile
        fields = ['nick_name', 'gender', 'birthday', 'address', 'mobile']


# 用于文件上传，修改头像
class UploadImageForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ['image']

website/templates/_heads.html
{% load staticfiles %}
<script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
<link href="http://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
<script src="https://cdn.bootcss.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>

<script src="{% static 'js/zlajax.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/sweetalert.css' %}">
<script src="{% static 'js/sweetalert.min.js' %}"></script>
<script src="{% static 'js/zlalert.js' %}"></script>

website/templates/_macros.html
{% macro static(filename) -%}
    {{ url_for("static",filename=filename) }}
{%- endmacro %}

website/templates/active_fail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>链接失效！！！</h1>
</body>
</html>

website/templates/front_base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% include "_heads.html" %}
    <link rel="stylesheet" href="{% static 'css/front_base.css' %}">
    <title>
        {% block title %}{% endblock %}
    </title>
    {% block head %}{% endblock %}
</head>
<body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">MOVIE PARADISE</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/">首页<span class="sr-only">(current)</span></a></li>
          </ul>
          <form class="navbar-form navbar-left">
            <div class="form-group">
              <input type="text" name="keywords" class="form-control" placeholder="请输入关键字">
            </div>
            <button type="submit" class="btn btn-default">搜索</button>
          </form>
          <ul class="nav navbar-nav navbar-right">
              {% if request.user.is_authenticated %}
                  <span id="login-tag" style="display: none"></span>
                  <li class="dropdown">
                      <a href="#" class="dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                        {{ request.user.username }}
                        <span class="caret"></span>
                      </a>
                      <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                        <li><a href="{% url 'users:user_info' %}">个人中心</a></li>
                        <li><a href="{% url 'logout' %}">注销</a></li>
                      </ul>
                  </li>
              {% else %}
                  <li><a href="{% url 'login' %}">登录</a></li>
                  <li><a href="{% url 'register' %}">注册</a></li>
              {% endif %}
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <div class="main-container">
        {% block body %}{% endblock %}
    </div>
</body>
</html>

website/templates/front_signbase.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
{#    <meta name="csrf-token" content="#">#}
    <title>{% block title %}{% endblock %}</title>
    <script src="http://cdn.bootcss.com/jquery/3.1.1/jquery.min.js"></script>
    <link href="http://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://cdn.bootcss.com/blueimp-md5/2.10.0/js/md5.min.js"></script>
    <script src="{% static 'js/zlparam.js' %}"></script>
    <script src="{% static 'js/zlajax.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/sweetalert.css' %}">
    <script src="{% static 'js/sweetalert.min.js' %}"></script>
    <script src="{% static 'js/zlalert.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/front_signbase.css' %}">
    {% block head %}

    {% endblock %}
</head>
<body>
    <div class="outer-box">
        <div class="logo-box">
            <a href="/">
                <img src="#" alt="">
            </a>
        </div>
        <h2 class="page-title">
            {% block h2_block %}{% endblock %}
        </h2>
        <div class="sign-box">
            {% block signbox %}{% endblock %}
        </div>
        <span style="display:none;" id="return-to-span">#</span>
    </div>
</body>
</html>

website/templates/my_comment.html
{% extends 'front_base.html' %}
{% load staticfiles %}
{% block title %}
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/front_postdetail.css' %}">
    <script src="{% static 'js/front_postdetail.js' %}"></script>


{% endblock %}

{% block body %}
    <div class="container_wrap">
        <div class="left-container">
            <div class="comment-list-group">
                <div class="comment-list-group-inner">
                    <div class="comment-title">
                        <p>评论列表</p>
                    </div>
                    <ul class="comment-list">
                        {% for comment in comments %}
                             <li>
                                <div class="comment-img">
                                    <a href="#"><img class="user-head" src="{{ MEDIA_URL }}{{ comment.author.image }}" alt=""></a>
                                </div>
                                <div class="comment-content">
                                    <p class="author-info">
                                        <span>{{ comment.author.username }}</span>
                                        <span>{{ comment.add_time }}</span>
                                    </p>
                                        <div class="origin-comment-group">
                                            <blockquote>
                                                {{ comment.author.username }} 发表于 {{ comment.add_time }}
                                                <p>{% autoescape off %}{{ comment.content }}{% endautoescape %}</p>
                                                <a href="{% url 'detail' comment.post.id %}">点击查看帖子详情</a>
                                            </blockquote>
                                        </div>
                                </div>
                            </li>
                        {% endfor %}

                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

website/templates/post_detail.html
{% extends 'front_base.html' %}
{% load staticfiles %}
{% block title %}
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/front_postdetail.css' %}">
    <script src="{% static 'js/front_postdetail.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static '/ueditor/UE/third-party/SyntaxHighlighter/shCoreDefault.css' %}">
        <script type="text/javascript" src="{% static '/ueditor/UE/third-party/SyntaxHighlighter/shCore.js' %}"></script>
        <script type="text/javascript" src="{% static '/ueditor/UE/ueditor.config.js' %}"></script>
        <script type="text/javascript" src="{% static '/ueditor/UE/ueditor.all.min.js' %}"></script>
        <script type="text/javascript" src="{% static '/ueditor/UE/lang/zh-cn/zh-cn.js' %}"></script>

        <script type="text/javascript">
            var ue = UE.getEditor('editor');
            SyntaxHighlighter.all();
        </script>
{% endblock %}

{% block body %}
    <div class="container_wrap">
        <div class="left-container">
            <div class="post-container">
                <div class="post-container-inner">
                    <div class="post-top">
                        <h2>{{ tie.title }}</h2>
                        <p class="post-info">
                            <span>发表时间：{{ tie.add_time }}</span>
                            <span>作者：{{ tie.author.username }}</span>
                            <span>所属板块：{{ tie.board.name }}</span>
                            <span class="comment-count">评论数：{{ tie.comment_num }}</span>
                            <span class="read-count">阅读数：{{ tie.read_num }}</span>
                        </p>
                    </div>
                    <div class="post-content">
                        {% autoescape off %}
                           {{ tie.content }}
                        {% endautoescape %}

                    </div>

                </div>
                <div class="comment-btn-group">
                    <form action="{% url 'comment' %}" method="post">
                        <input type="hidden" name="tie_id" value="{{ tie.id }}">
                    <script id="editor" type="text/plain" name="content"></script>
                        <button type="submit" class="btn btn-danger" id="submit-btn">发表评论</button>
                    {% csrf_token %}
                    </form>
                </div>
            </div>
            <div class="comment-list-group">
                <div class="comment-list-group-inner">
                    <div class="comment-title">
                        <p>评论列表</p>
                    </div>
                    <ul class="comment-list">
                        {% for comment in comments %}
                             <li>
                                <div class="comment-img">
                                    <a href="#"><img class="user-head" src="{{ MEDIA_URL }}{{ comment.author.image }}" alt=""></a>
                                </div>
                                <div class="comment-content">
                                    <p class="author-info">
                                        <span>{{ comment.author.username }}</span>
                                        <span>{{ comment.add_time }}</span>
                                    </p>
                                        <div class="origin-comment-group">
                                            <blockquote>
                                                {{ comment.author.username }} 发表于 {{ comment.add_time }}
                                                <p>{% autoescape off %}{{ comment.content }}{% endautoescape %}</p>
                                            </blockquote>
                                        </div>
                                </div>
                            </li>
                        {% endfor %}


                    </ul>
                </div>
            </div>
        </div>
        <div class="right-container">
            <div class="author-group">
                <div class="avatar-group">
                    <a href="{% url 'users:user_info' %}"><img src="{{ MEDIA_URL }}{{ tie.author.image }}" alt="" class="avatar-img"></a>
                </div>
                <p class="username">{{ tie.author.username }}</p>
                <p class="txt">昵称：{{ tie.author.nick_name }}</p>
                <div class="btn-box">
                    <a href="{% url 'users:user_info' %}" target="_blank" class="btn btn-warning">Ta的主页</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

website/templates/register.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
    <title>用户注册</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
</head>
<body>
<div class="loginbox dialogbox">
    <h1>账号登录</h1>
    <div class="close jsCloseDialog"><img src="{% static 'images/dig_close.png' %}"/></div>
    <div class="cont">
        <form id="jsLoginForm" autocomplete="off">
            <div class="box">
                <span class="word3">用户名</span>
                <input type="text" name="account_l" id="account_l" placeholder="手机号/邮箱" />
            </div>
            <div class="box">
                <span class="word2">密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码</span>
                <input type="password" name="password_l" id="password_l" placeholder="请输入您的密码"/>
            </div>
            <div class="error btns login-form-tips" id="jsLoginTips"></div> <!--登录错误提示-->
            <div class="btns">
                <span><input type="checkbox" id="jsAutoLogin" />&nbsp;自动登录</span>
                <span class="forget btn fr">忘记密码</span>
            </div>
            <div class="button">
                <input type="button" value="登录" id="jsLoginBtn" />
            </div>
            <div class="btns">
                <span class="fr">没有账号？<span class="regist btn">立即注册</span></span>
            </div>
        </form>
    </div>
</div>
<div class="dialog" id="jsDialog">
    <!--提示弹出框-->
    <div class="successbox dialogbox" id="jsSuccessTips">
        <h1>成功提交</h1>
        <div class="close jsCloseDialog"><img src="{% static 'images/dig_close.png' %}"/></div>
        <div class="cont">
            <h2>您的需求提交成功！</h2>
            <p></p>
        </div>
    </div>
    <div  class="noactivebox dialogbox" id="jsUnactiveForm" >
        <h1>邮件验证提示</h1>
        <div class="close jsCloseDialog"><img src="{% static 'images/dig_close.png' %}"/></div>
        <div class="center">
            <img src="{% static 'images/send.png' %}"/>
            <p>我们已经向您的邮箱<span class="green" id="jsEmailToActive">12@13.com</span>发送了邮件，<br/>为保证您的账号安全，请及时验证邮箱</p>
            <p class="a"><a class="btn" id="jsGoToEmail" target="_blank" href="http://mail.qq.com">去邮箱验证</a></p>
            <p class="zy_success upmove"></p>
            <p style="display: none;" class="sendE2">没收到，您可以查看您的垃圾邮件和被过滤邮件，也可以再次发送验证邮件（<span class="c5c">60s</span>）</p>
            <p class="sendE">没收到，您可以查看您的垃圾邮件和被过滤邮件，<br/>也可以<span class="c5c green" id="jsSenEmailAgin" style="cursor: pointer;">再次发送验证邮件</span></p>
        </div>
    </div>
</div>

<div class="bg" id="dialogBg"></div>
<header>
    <div class="c-box fff-box">
        <div class="wp header-box">
            <p class="fl hd-tips">MOVIE PARADISE&nbsp;用户注册</p>
            <ul class="fr hd-bar">
                <li>服务电话：<span>2222222</span></li>
                <li><a href="{% url 'login' %}">[登录]</a></li>
                <li class="active"><a href="{% url 'register' %}">[注册]</a></li>
            </ul>
        </div>
    </div>
</header>
<section>
    <div class="c-box bg-box">
        <div class="login-box clearfix">
            <div class="hd-login clearfix">
                <a class="index-logo" href="#"></a>
                <h1>用户注册</h1>
                <a class="index-font" href="{% url 'index' %}">回到首页</a>
            </div>
            <div class="fl slide">
                <div class="imgslide">
                    <ul class="imgs">

                        <li><a href="https://movie.douban.com/subject/4206436/" target="_blank"><img width="483" height="472" src="{% static 'images/banner/banner01.jpg' %}" /></a></li>

                        <li><a href="https://movie.douban.com/subject/1820156/" target="_blank"><img width="483" height="472" src="{% static 'images/banner/banner02.jpg' %}" /></a></li>

                        <li><a href="https://movie.douban.com/subject/1307914/" target="_blank"><img width="483" height="472" src="{% static 'images/banner/banner03.jpg' %}" /></a></li>

                    </ul>
                </div>
                <div class="unslider-arrow prev"></div>
                <div class="unslider-arrow next"></div>
            </div>
            <div class="fl form-box">
                <div class="tab">
                    <!--<h2 class="active">手机注册</h2>-->
                    <h2>邮箱注册</h2>
                </div>
                <div class="tab-form">
                    <form id="email_register_form" method="post" action="{% url 'register' %}" autocomplete="off">
                        <input type='hidden' name='csrfmiddlewaretoken' value='gTZljXgnpvxn0fKZ1XkWrM1PrCGSjiCZ' />
                        <div class="form-group marb20 {% if register_form.errors.email %}errorput{% endif %}">
                            <label>邮&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;箱</label>
                            <input  type="text" id="id_email" name="email" value="{% ifnotequal None register_form.email.value %}{{ register_form.email.value }}{% endifnotequal %}" placeholder="请输入您的邮箱地址" />
                        </div>
                        <div class="form-group marb8 {% if register_form.errors.password %}errorput{% endif %}">
                            <label>密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码</label>
                            <input type="password" id="id_password" name="password"  value="{% ifnotequal None register_form.password.value %}{{ register_form.password.value }}{% endifnotequal %}" placeholder="请输入6-20位非中文字符密码" />
                        </div>
                        <div class="form-group marb8 captcha1 ">
                            <label>验&nbsp;证&nbsp;码</label>
                            {{ register_form.captcha }}
                        </div>
                        <div class="error btns" id="jsEmailTips">{% for key,error in register_form.errors.items %}
                        {{ error }}{% endfor %}</div>
                        <div class="auto-box marb8">
                        </div>
                        <input class="btn btn-green" id="jsEmailRegBtn" type="submit" value="注册并登录" />
                    <input type='hidden' name='csrfmiddlewaretoken' value='5I2SlleZJOMUX9QbwYLUIAOshdrdpRcy' />
                    {% csrf_token %}
                    </form>
                </div>
                <p class="form-p">已有账号？<a href="{% url 'login' %}">[立即登录]</a></p>
            </div>
        </div>
    </div>
</section>

<input id="isLogin" type="hidden" value="False"/>
<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/validateDialog.js' %}"  type="text/javascript"></script>
<script src="{% static 'js/login.js' %}"  type="text/javascript"></script>
</body>
</html>

website/templates/send_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>信息已经发送到邮箱, 请查收！！！</h1>
</body>
</html>

website/templates/usercenter-info.html
{% extends 'userscnter_base.html' %}

{% block title %}个人信息{% endblock %}

{% block custom_bread %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'users:user_info' %}">个人中心</a>></li>
                <li>我的资料</li>
            </ul>
        </div>
    </section>
{% endblock %}


{% block right_content %}
     <div class="right">
		<div class="personal_des ">
			<div class="head" style="border:1px solid #eaeaea;">
				<h1>个人信息</h1>
			</div>
			<div class="inforcon">
				<div class="left" style="width:242px;">
                    <iframe id='frameFile' name='frameFile' style='display: none;'></iframe>
                    <form class="clearfix" id="jsAvatarForm" enctype="multipart/form-data" autocomplete="off" method="post" action="{% url 'users:image_upload' %}" target='frameFile'>
                        <label class="changearea" for="avatarUp">
                            <span id="avatardiv" class="pic">
                                <img width="100" height="100" class="js-img-show" id="avatarShow" src="{{ MEDIA_URL }}{{ request.user.image }}"/>
                            </span>
                            <span class="fl upload-inp-box" style="margin-left:70px;">
                                <span class="button btn-green btn-w100" id="jsAvatarBtn">修改头像</span>
                                <input type="file" name="image" id="avatarUp" class="js-img-up"/>
                            </span>
                        </label>
                        <input type='hidden' name='csrfmiddlewaretoken' value='799Y6iPeEDNSGvrTu3noBrO4MBLv6enY' />
                        {% csrf_token %}
                    </form>
                    <div style="border-top:1px solid #eaeaea;margin-top:30px;">
                        <a class="button btn-green btn-w100" id="jsUserResetPwd" style="margin:80px auto;width:100px;">修改密码</a>
                    </div>
				</div>
				<form class="perinform" id="jsEditUserForm" autocomplete="off">
					<ul class="right">
						<li>昵&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;称：
                           <input type="text" name="nick_name" id="nick_name" value="{{ request.user.nick_name }}" maxlength="10">
                            <i class="error-tips"></i>
                        </li>
						<li>生&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;日：
                           <input type="text" id="birth_day" name="birthday" value="{{ request.user.birthday|default:'保密' }}" readonly="readonly"/>
                            <i class="error-tips"></i>
						</li>
						<li>性&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;别：
							<label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="radio"  name="gender" value="male"  {% if request.user.gender == 'male' %}checked="checked"{% endif %}>男</label>
							<label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="radio" name="gender" value="female" {% if request.user.gender == 'female' %}checked="checked"{% endif %}>女</label>
						</li>
						<li class="p_infor_city">地&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;址：
                            <input type="text" name="address" id="address" placeholder="请输入你的地址" value="{{ request.user.address }}" maxlength="10">
						    <i class="error-tips"></i>
                        </li>
						<li>手&nbsp;&nbsp;机&nbsp;&nbsp;号：
                            <input type="text" name="mobile" id="mobile" placeholder="请输入你的手机号码" value="{{ request.user.mobile|default:'2222222' }}" maxlength="10">
                        </li>
                        <li>邮&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;箱：
                        	<input class="borderno" type="text" name="email" readonly="readonly" value="{{ request.user.email }}"/>
                            <span class="green changeemai_btn">[修改]</span>
                    	</li>
						<li class="button heibtn">
							<input type="button" id="jsEditUserBtn" value="保存">
						</li>
					</ul>
                    <input type='hidden' name='csrfmiddlewaretoken' value='799Y6iPeEDNSGvrTu3noBrO4MBLv6enY' />
				{% csrf_token %}
                </form>
			</div>
		</div>
	</div>
{% endblock %}